### ISSUE TITLE
bug in homework set manager

### ISSUE THREAD

**Issue by mgage** [pstaabp/webwork2#21]
In the file htdocs/html-templates/homework-manager.html there are several

<<<<HEAD lines.  I've fixed them with my best guess.

I cannot change the dates on a problem set, save them and get them to stick.
The dates appear to be changed but if I go back to the main course page and then
inspect the set again the dates have reverted to the original dates.

The main menu is not functional on the homeworkmanager page.  I believe the other 
menu on the left is also not functioning.

I have been able to crash the server (it ceases to respond until being restarted) by changing the date, going to the first page of the course using the bread crumbs and --- I get a server not available warning.

**Comment by pstaabp** [comment]
Which View of the Homework Manager are you in?  I'm guessing it is the "All Sets" View, because I notice that now.  I was switching interface over.  I'll look into it today.

Peter

**Comment by pstaabp** [comment]
I think I have taken care of it.  Let me know.
