### ISSUE TITLE
Use Bootstrap Navigation Elements

### ISSUE THREAD

**Issue by goehle** [pstaabp/webwork2#29]
The navigation and buttons in the homework manager look a little off.  (There is a lot of grey on gray, sizes don't always match up correctly, elements can be a little "floaty", etc...)

A lot of this could be fixed with standard bootstrap elements.  There are button group, button dropdown menues, navigation bars, nav lists, etc... that could help look the page look cleaner.  

http://getbootstrap.com/2.3.2/components.html

**Comment by pstaabp** [comment]
I this this is a result of switching to boostrap 3.0 which I just did.  I'll double check that I have this done.

**Comment by pstaabp** [comment]
This has been fixed.
